import { defineConfig } from "tsup";

export default defineConfig({
	// Vercel's rewrite destination `/api` resolves to api/index.js — that file must exist.
	// api/[[...path]].js is the optional catch-all so /api/v1/* reaches Express (index alone would not).
	entry: {
		"api/index": "handler/index.ts",
		"api/[[...path]]": "handler/index.ts",
	},
	format: ["cjs"],
	outDir: ".",
	outExtension: () => ({ js: ".js" }),
	splitting: false,
	clean: false,
	target: "node20",
	platform: "node",
	/** Workspace packages are ESM (`"type": "module"`); CJS output must not `require()` them — bundle them in. */
	noExternal: ["openquok-common"],
	external: [
		"fs",
		"path",
		"http",
		"https",
		"crypto",
		"stream",
		"url",
		"util",
		"events",
		"buffer",
		"querystring",
		"os",
		"net",
		"tls",
		"zlib",
		"child_process",
		"cluster",
		"dgram",
		"dns",
		"readline",
		"repl",
		"tty",
		"v8",
		"vm",
		"worker_threads",
		"assert",
		"async_hooks",
		"console",
		"constants",
		"domain",
		"inspector",
		"module",
		"perf_hooks",
		"process",
		"punycode",
		"string_decoder",
		"sys",
		"timers",
		"trace_events",
		"wasi",
	],
	treeshake: true,
	sourcemap: false,
	tsconfig: "tsconfig.json",
	banner: {
		js: "/* Bundled by tsup for Vercel */",
	},
});
