export type LinkDirectoryConfig = {
	endpoints: {
		getPublishedSites: string;
		getPublishedHubStats: string;
		getPublishedSiteBySlug: (siteSlug: string) => string;
		getActiveCategories: string;
		getActiveTags: string;
		getOpportunityTypes: string;
		createSubmission: string;
		getMySavedSites: string;
		putMySavedSites: string;
		putMySavedSitesOrder: string;
		patchSavedSiteOutreachCompletion: (siteId: string) => string;
		getAdminSites: string;
		getSiteById: (siteId: string) => string;
		createSite: string;
		updateSite: (siteId: string) => string;
		deleteSite: (siteId: string) => string;
		createOpportunity: (siteId: string) => string;
		updateOpportunity: (opportunityId: string) => string;
		deleteOpportunity: (opportunityId: string) => string;
		getAllCategories: string;
		createCategory: string;
		updateCategory: (categoryId: string) => string;
		deleteCategory: (categoryId: string) => string;
		getAllTags: string;
		getTagGroups: string;
		createTagGroup: string;
		updateTagGroup: (tagGroupId: string) => string;
		deleteTagGroup: (tagGroupId: string) => string;
		createTag: string;
		updateTag: (tagId: string) => string;
		deleteTag: (tagId: string) => string;
		getAdminSubmissions: string;
		reviewSubmission: (submissionId: string) => string;
		postSiteViews: (siteId: string) => string;
		postSiteLikes: (siteId: string) => string;
		getSiteComments: (siteId: string) => string;
		createSiteComment: (siteId: string) => string;
		upsertSiteRating: (siteId: string) => string;
		getAdminSiteComments: string;
		approveSiteComment: (commentId: string) => string;
		deleteSiteComment: (commentId: string) => string;
	};
};
