export const CENTERED_DARK_CTA_BANNER_PATH_TEXT =
	'START FOR $0 • DRAFT • REVIEW • APPROVE • PUBLISH • START FOR $0 • DRAFT • REVIEW • APPROVE • PUBLISH • START FOR $0 • DRAFT • REVIEW • APPROVE • PUBLISH • START FOR $0 • DRAFT • REVIEW • APPROVE • PUBLISH •';
