-- ---------------------------
-- MODULE NAME: Link Directory
-- MODULE DATE: 20251001
-- MODULE SCOPE: Seed exemplar sites and opportunities (site sort_order 0; hub default sort is domain rating; opportunity sort_order 10/20/30 orders playbooks)
-- ---------------------------

BEGIN;

INSERT INTO public.link_directory_sites (
    id,
    published_at,
    slug,
    title,
    site_url,
    short_description,
    long_description,
    domain_rating,
    monthly_visits,
    metrics_source,
    metrics_updated_at,
    category_id,
    is_openquok_auth_supported,
    openquok_channel_slug,
    is_admin_published,
    sort_order,
    tag_slugs
) VALUES
    (
        'd5f7d000-0010-4000-a000-000000000001',
        NOW(),
        'reddit',
        'Reddit',
        'https://www.reddit.com',
        'Community posts, profiles, and Q&A threads — follow each subreddit''s self-promotion rules.',
        'Reddit offers several link surfaces: feed posts, profile bios, and helpful answers in comment threads. Moderation varies by community.',
        91,
        1700000000,
        'editor_estimate',
        NOW(),
        'd5f7d000-0001-4000-a000-000000000001',
        false,
        NULL,
        true,
        0,
        ARRAY['community-moderated']::text[]
    ),
    (
        'd5f7d000-0010-4000-a000-000000000002',
        NOW(),
        'bluesky',
        'Bluesky',
        'https://bsky.app',
        'Decentralized social network with posts, profiles, and threads.',
        'Bluesky supports website links on profiles and in posts. Threads can carry a primary link when you schedule multi-post content.',
        78,
        25000000,
        'editor_estimate',
        NOW(),
        'd5f7d000-0001-4000-a000-000000000001',
        true,
        'bluesky',
        true,
        0,
        ARRAY['high-dr']::text[]
    ),
    (
        'd5f7d000-0010-4000-a000-000000000003',
        NOW(),
        'facebook',
        'Facebook',
        'https://www.facebook.com',
        'Pages, profiles, posts, and comments for brand visibility.',
        'Facebook Pages and profiles can surface your site URL. Posts and follow-up comments extend reach when policy allows external links.',
        96,
        2800000000,
        'editor_estimate',
        NOW(),
        'd5f7d000-0001-4000-a000-000000000001',
        true,
        'facebook',
        true,
        0,
        ARRAY['high-dr']::text[]
    ),
    (
        'd5f7d000-0010-4000-a000-000000000004',
        NOW(),
        'uneed',
        'Uneed',
        'https://uneed.best',
        'Launch directory with paid product features and a free maker profile.',
        'Uneed combines a paid launch slot with a free profile link. Plan budget and copy before submitting.',
        42,
        120000,
        'editor_estimate',
        NOW(),
        'd5f7d000-0001-4000-a000-000000000002',
        false,
        NULL,
        true,
        0,
        ARRAY[]::text[]
    ),
    (
        'd5f7d000-0010-4000-a000-000000000005',
        NOW(),
        'open-launch',
        'Open Launch',
        'https://openlaunch.io',
        'Guest posts and launch coverage for startups.',
        'Open Launch accepts guest contributions with editorial review. Useful for a contextual article when your story fits their audience — confirm link treatment with editors.',
        35,
        45000,
        'editor_estimate',
        NOW(),
        'd5f7d000-0001-4000-a000-000000000002',
        false,
        NULL,
        true,
        0,
        ARRAY[]::text[]
    ),
    (
        'd5f7d000-0010-4000-a000-000000000006',
        NOW(),
        'awesome-selfhosted',
        'Awesome Selfhosted',
        'https://awesome-selfhosted.net',
        'Community-maintained catalog of self-hosted software — submit via pull request.',
        'The awesome-selfhosted project curates qualifying self-hosted tools on GitHub. A merged list entry surfaces your project URL to maintainers and readers; follow CONTRIBUTING rules and category placement.',
        72,
        800000,
        'editor_estimate',
        NOW(),
        'd5f7d000-0001-4000-a000-000000000004',
        false,
        NULL,
        true,
        0,
        ARRAY['community-moderated', 'high-dr']::text[]
    ),
    (
        'd5f7d000-0010-4000-a000-000000000007',
        NOW(),
        'github',
        'GitHub',
        'https://github.com',
        'Profiles, project sites, and package pages on github.com — each surface has different link rules.',
        'GitHub hosts several distinct backlink paths: a profile README repo, GitHub Pages sites, and container or package listings on GitHub Container Registry (GHCR). Pick the workflow that matches your product (personal brand, docs site, or shipped artifact).',
        97,
        520000000,
        'editor_estimate',
        NOW(),
        'd5f7d000-0001-4000-a000-000000000001',
        false,
        NULL,
        true,
        0,
        ARRAY['high-dr', 'github']::text[]
    )
ON CONFLICT (id) DO UPDATE SET
    slug = EXCLUDED.slug,
    title = EXCLUDED.title,
    site_url = EXCLUDED.site_url,
    short_description = EXCLUDED.short_description,
    long_description = EXCLUDED.long_description,
    domain_rating = EXCLUDED.domain_rating,
    monthly_visits = EXCLUDED.monthly_visits,
    metrics_source = EXCLUDED.metrics_source,
    metrics_updated_at = EXCLUDED.metrics_updated_at,
    category_id = EXCLUDED.category_id,
    is_openquok_auth_supported = EXCLUDED.is_openquok_auth_supported,
    openquok_channel_slug = EXCLUDED.openquok_channel_slug,
    is_admin_published = EXCLUDED.is_admin_published,
    sort_order = EXCLUDED.sort_order,
    tag_slugs = EXCLUDED.tag_slugs,
    published_at = COALESCE(public.link_directory_sites.published_at, EXCLUDED.published_at);

INSERT INTO public.link_directory_site_tags_association (site_id, link_directory_tag_id)
SELECT s.id, t.id
FROM public.link_directory_sites s
JOIN public.link_directory_tags t ON t.slug = ANY (s.tag_slugs)
WHERE s.id IN (
    'd5f7d000-0010-4000-a000-000000000001',
    'd5f7d000-0010-4000-a000-000000000002',
    'd5f7d000-0010-4000-a000-000000000003',
    'd5f7d000-0010-4000-a000-000000000004',
    'd5f7d000-0010-4000-a000-000000000005',
    'd5f7d000-0010-4000-a000-000000000006',
    'd5f7d000-0010-4000-a000-000000000007'
)
ON CONFLICT DO NOTHING;

INSERT INTO public.link_directory_opportunities (
    id,
    site_id,
    published_at,
    slug,
    title,
    opportunity_type_id,
    effort,
    approval_mode,
    approval_time_hint,
    dofollow,
    cost_tier,
    cost_note,
    description,
    steps,
    openquok_cta_kind,
    openquok_channel_slug,
    openquok_plug_name,
    cta_href,
    cta_label,
    sort_order,
    is_admin_published
) VALUES
    (
        'd5f7d000-0020-4000-a000-000000000001',
        'd5f7d000-0010-4000-a000-000000000001',
        NOW(),
        'subreddit-post',
        'Subreddit post',
        'd5f7d000-0004-4000-a000-000000000001',
        'medium',
        'manual_review',
        'Varies by subreddit moderators',
        'nofollow',
        'free',
        NULL,
        'Share a post where subreddit rules allow promotional or showcase content. Outbound links in posts use rel=nofollow ugc.',
        '[{"order":1,"title":"Pick a subreddit","body":"Read rules and recent posts to match tone."},{"order":2,"title":"Draft value-first copy","body":"Lead with insight; place your link once where allowed."}]'::jsonb,
        'none',
        NULL,
        NULL,
        'https://www.reddit.com/submit',
        'Open Reddit submit',
        10,
        true
    ),
    (
        'd5f7d000-0020-4000-a000-000000000002',
        'd5f7d000-0010-4000-a000-000000000001',
        NOW(),
        'profile-bio',
        'Profile bio link',
        'd5f7d000-0004-4000-a000-000000000002',
        'easy',
        'instant',
        NULL,
        'nofollow',
        'free',
        NULL,
        'Add your site to your Reddit profile description. Reddit marks outbound profile links nofollow (ugc), same as posts and comments.',
        '[{"order":1,"title":"Edit profile","body":"Settings → Profile → About description."}]'::jsonb,
        'none',
        NULL,
        NULL,
        'https://www.reddit.com/settings/profile',
        'Edit profile',
        20,
        true
    ),
    (
        'd5f7d000-0020-4000-a000-000000000003',
        'd5f7d000-0010-4000-a000-000000000001',
        NOW(),
        'helpful-answer',
        'Helpful answer link',
        'd5f7d000-0004-4000-a000-000000000004',
        'hard',
        'manual_review',
        'Community voting and mod removal',
        'nofollow',
        'free',
        NULL,
        'Answer a question with genuine help and a single relevant link when permitted. Comment links are nofollow ugc on Reddit.',
        '[]'::jsonb,
        'external_doc',
        NULL,
        NULL,
        'https://www.openquok.com/docs',
        'Read plug docs',
        30,
        true
    ),
    (
        'd5f7d000-0020-4000-a000-000000000004',
        'd5f7d000-0010-4000-a000-000000000002',
        NOW(),
        'profile-website',
        'Profile website field',
        'd5f7d000-0004-4000-a000-000000000002',
        'easy',
        'instant',
        NULL,
        'nofollow',
        'free',
        NULL,
        'Set the website URL on your Bluesky profile. Treat outbound social links as nofollow for SEO; value is referral traffic and brand discovery.',
        '[{"order":1,"title":"Open profile settings","body":"Add your primary marketing URL."}]'::jsonb,
        'connect_channel',
        'bluesky',
        NULL,
        NULL,
        'Connect Bluesky',
        10,
        true
    ),
    (
        'd5f7d000-0020-4000-a000-000000000005',
        'd5f7d000-0010-4000-a000-000000000002',
        NOW(),
        'scheduled-thread',
        'Scheduled thread with link',
        'd5f7d000-0004-4000-a000-000000000005',
        'medium',
        'instant',
        NULL,
        'nofollow',
        'free',
        NULL,
        'Publish a multi-post thread with your link in the lead post. Post links on Bluesky should be planned as nofollow for ranking; they still drive clicks.',
        '[]'::jsonb,
        'schedule_post',
        'bluesky',
        NULL,
        NULL,
        'Schedule with OpenQuok',
        20,
        true
    ),
    (
        'd5f7d000-0020-4000-a000-000000000007',
        'd5f7d000-0010-4000-a000-000000000003',
        NOW(),
        'page-about-link',
        'Create Facebook Page with website',
        'd5f7d000-0004-4000-a000-000000000002',
        'easy',
        'instant',
        NULL,
        'nofollow',
        'free',
        NULL,
        'Set up a Facebook Page and add your primary website in About before you post link updates. Facebook typically nofollows outbound links, including Page website fields.',
        '[{"order":1,"title":"Create or claim a Page","body":"Use a Facebook Page for your brand (not only a personal profile)."},{"order":2,"title":"Add your website in About","body":"Open Page settings → About and enter your site URL in the Website field."},{"order":3,"title":"Save and verify","body":"Publish changes and confirm the link works from the public Page view."}]'::jsonb,
        'connect_channel',
        'facebook',
        NULL,
        NULL,
        'Connect Facebook',
        10,
        true
    ),
    (
        'd5f7d000-0020-4000-a000-000000000006',
        'd5f7d000-0010-4000-a000-000000000003',
        NOW(),
        'page-post',
        'Facebook Page post',
        'd5f7d000-0004-4000-a000-000000000001',
        'medium',
        'instant',
        NULL,
        'nofollow',
        'free',
        NULL,
        'After your Page lists your website, publish or schedule a Page post with a link preview. Link previews in posts are nofollow from facebook.com.',
        '[{"order":1,"title":"Confirm Page setup","body":"Finish Page About with your website URL before posting external links."},{"order":2,"title":"Draft the post","body":"Write a short update with context and the URL you want to promote."},{"order":3,"title":"Publish or schedule","body":"Post immediately or schedule for when your audience is most active."}]'::jsonb,
        'schedule_post',
        'facebook',
        NULL,
        NULL,
        'Schedule post',
        20,
        true
    ),
    (
        'd5f7d000-0020-4000-a000-000000000008',
        'd5f7d000-0010-4000-a000-000000000004',
        NOW(),
        'paid-launch',
        'Paid launch listing',
        'd5f7d000-0004-4000-a000-000000000006',
        'medium',
        'manual_review',
        'Usually within a few business days',
        'dofollow',
        'paid',
        'Check current pricing on Uneed',
        'Featured launch placement with a prominent product link. Third-party launch directories usually link to your site without nofollow on listing pages — confirm on the live Uneed product card.',
        '[]'::jsonb,
        'external_doc',
        NULL,
        NULL,
        'https://uneed.best',
        'View Uneed pricing',
        10,
        true
    ),
    (
        'd5f7d000-0020-4000-a000-000000000009',
        'd5f7d000-0010-4000-a000-000000000004',
        NOW(),
        'free-profile',
        'Free maker profile',
        'd5f7d000-0004-4000-a000-000000000002',
        'easy',
        'instant',
        NULL,
        'dofollow',
        'free',
        NULL,
        'Create a profile with your project URL at no cost. Maker profiles on Uneed typically use dofollow listing links; verify rel on your public profile URL.',
        '[]'::jsonb,
        'none',
        NULL,
        NULL,
        'https://uneed.best',
        'Create profile',
        20,
        true
    ),
    (
        'd5f7d000-0020-4000-a000-000000000010',
        'd5f7d000-0010-4000-a000-000000000005',
        NOW(),
        'guest-article',
        'Guest article',
        'd5f7d000-0004-4000-a000-000000000007',
        'hard',
        'manual_review',
        'Editorial calendar',
        'unknown',
        'paid',
        'Sponsorship or placement fees may apply',
        'Pitch a story that fits Open Launch readers; include contextual links in the draft. Dofollow vs nofollow depends on Open Launch’s editorial policy — confirm before you publish.',
        '[{"order":1,"title":"Review guidelines","body":"Align topic with their startup audience."},{"order":2,"title":"Submit pitch","body":"Include outline and target URL."}]'::jsonb,
        'external_doc',
        NULL,
        NULL,
        'https://openlaunch.io',
        'Open Launch site',
        10,
        true
    ),
    (
        'd5f7d000-0020-4000-a000-000000000011',
        'd5f7d000-0010-4000-a000-000000000006',
        NOW(),
        'list-pr',
        'Awesome list pull request',
        'd5f7d000-0004-4000-a000-000000000008',
        'hard',
        'manual_review',
        'Maintainer review',
        'nofollow',
        'free',
        NULL,
        'Open a PR on the awesome-selfhosted repository that adds your tool in the correct category with a concise description. Merged list links render on github.com with nofollow like other README links.',
        '[{"order":1,"title":"Confirm eligibility","body":"Project must be self-hostable and actively maintained per their CONTRIBUTING guide."},{"order":2,"title":"Open pull request","body":"Use the list format; one entry per tool; link your homepage or docs URL."}]'::jsonb,
        'none',
        NULL,
        NULL,
        'https://github.com/awesome-selfhosted/awesome-selfhosted',
        'Open list repository',
        10,
        true
    ),
    (
        'd5f7d000-0020-4000-a000-000000000012',
        'd5f7d000-0010-4000-a000-000000000007',
        NOW(),
        'profile-readme',
        'Profile README',
        'd5f7d000-0004-4000-a000-000000000002',
        'easy',
        'instant',
        NULL,
        'nofollow',
        'free',
        NULL,
        'Create a public repository named like your username with a README.md — GitHub renders it on your profile. README and profile website links on github.com are nofollow.',
        '[{"order":1,"title":"Create the profile repo","body":"New repository named exactly your GitHub username (e.g. octocat/octocat), public, with a README."},{"order":2,"title":"Write the README","body":"Introduce yourself or your product and include one clear link to your marketing site or docs."},{"order":3,"title":"Set profile website","body":"Profile → Edit profile → Website — paste the same primary URL for visitors who skip the README."}]'::jsonb,
        'none',
        NULL,
        NULL,
        'https://docs.github.com/en/account-and-profile/setting-up-and-managing-your-github-profile/customizing-your-profile/managing-your-profile-readme',
        'Profile README docs',
        10,
        true
    ),
    (
        'd5f7d000-0020-4000-a000-000000000013',
        'd5f7d000-0010-4000-a000-000000000007',
        NOW(),
        'github-pages-site',
        'GitHub Pages site',
        'd5f7d000-0004-4000-a000-000000000001',
        'medium',
        'instant',
        NULL,
        'dofollow',
        'free',
        NULL,
        'Publish a static site or docs on github.io (or a custom domain). Unlike READMEs on github.com, Pages serves your HTML without adding rel=nofollow to outbound links you author.',
        '[{"order":1,"title":"Choose Pages source","body":"Repository Settings → Pages — deploy from a branch or GitHub Actions workflow."},{"order":2,"title":"Publish content","body":"Add HTML or Markdown with contextual copy; place your canonical product URL in header, footer, or About page."},{"order":3,"title":"Verify rel attributes","body":"Inspect a live outbound link on your Pages URL — it should not include nofollow unless you added it in your template or markup."}]'::jsonb,
        'none',
        NULL,
        NULL,
        'https://docs.github.com/en/pages/getting-started-with-github-pages/creating-a-github-pages-site',
        'GitHub Pages guide',
        20,
        true
    ),
    (
        'd5f7d000-0020-4000-a000-000000000014',
        'd5f7d000-0010-4000-a000-000000000007',
        NOW(),
        'ghcr-container-package',
        'Container package (GHCR)',
        'd5f7d000-0004-4000-a000-000000000008',
        'medium',
        'instant',
        NULL,
        'nofollow',
        'free',
        NULL,
        'Publish an OCI image to GitHub Container Registry under your user or org. The package page lives on github.com — README and repo links use GitHub’s nofollow sanitizer, similar to profile READMEs.',
        '[{"order":1,"title":"Publish the image","body":"Push a tagged image to ghcr.io with a workflow or docker push; link the package to the source repository."},{"order":2,"title":"Set package metadata","body":"Add description and source-repo metadata; treat external links as discovery for people, not dofollow SEO from github.com."},{"order":3,"title":"Surface install docs","body":"In the repo README, link the GHCR pull command and your primary site — expect nofollow on github.com-rendered anchors."}]'::jsonb,
        'none',
        NULL,
        NULL,
        'https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-container-registry',
        'Container registry docs',
        30,
        true
    )
ON CONFLICT (id) DO UPDATE SET
    site_id = EXCLUDED.site_id,
    slug = EXCLUDED.slug,
    title = EXCLUDED.title,
    opportunity_type_id = EXCLUDED.opportunity_type_id,
    effort = EXCLUDED.effort,
    approval_mode = EXCLUDED.approval_mode,
    approval_time_hint = EXCLUDED.approval_time_hint,
    dofollow = EXCLUDED.dofollow,
    cost_tier = EXCLUDED.cost_tier,
    cost_note = EXCLUDED.cost_note,
    description = EXCLUDED.description,
    steps = EXCLUDED.steps,
    openquok_cta_kind = EXCLUDED.openquok_cta_kind,
    openquok_channel_slug = EXCLUDED.openquok_channel_slug,
    openquok_plug_name = EXCLUDED.openquok_plug_name,
    cta_href = EXCLUDED.cta_href,
    cta_label = EXCLUDED.cta_label,
    sort_order = EXCLUDED.sort_order,
    is_admin_published = EXCLUDED.is_admin_published,
    published_at = COALESCE(public.link_directory_opportunities.published_at, EXCLUDED.published_at);

UPDATE public.link_directory_sites s
SET tag_slugs = sub.slugs
FROM (
    SELECT
        sta.site_id,
        ARRAY_AGG(t.slug ORDER BY t.slug) AS slugs
    FROM public.link_directory_site_tags_association sta
    INNER JOIN public.link_directory_tags t ON t.id = sta.link_directory_tag_id
    GROUP BY sta.site_id
) sub
WHERE s.id = sub.site_id;

-- ---------------------------
-- END OF FILE
-- ---------------------------

COMMIT;
