export {
	WRITER_API_DOCS_URL,
	REWRITER_API_DOCS_URL,
	WRITER_SOFT_OPT_IN_STORAGE_KEY,
	REWRITER_SOFT_OPT_IN_STORAGE_KEY,
	COMPOSER_WRITER_BASE_SHARED_CONTEXT,
	COMPOSER_WRITER_LENGTH_SHORT_MAX_CHARS,
	COMPOSER_WRITER_LENGTH_MEDIUM_MAX_CHARS,
	COMPOSER_WRITER_DEFAULTS,
	COMPOSER_REWRITER_DEFAULTS,
	COMPOSER_WRITER_SUGGESTIONS,
	COMPOSER_REWRITER_REFINE_ACTIONS,
	type ComposerRewriterRefineAction,
	type ComposerRewriterRefineActionId
} from '$lib/ai-writer/constants/config';

export {
	isWriterSupported,
	isRewriterSupported,
	getWriterAvailability,
	getRewriterAvailability,
	type WriterAvailability,
	type RewriterAvailability,
	createComposerWriter,
	createComposerRewriter,
	type CreateComposerWriterOptions,
	type CreateComposerRewriterOptions,
	type WriterSession,
	type RewriterSession,
	writeDraftStreaming,
	rewriteDraftStreaming,
	type WriteDraftStreamingOptions,
	type RewriteDraftStreamingOptions,
	destroyAiSession,
	destroyWriter,
	hasWriterSoftOptIn,
	acceptWriterSoftOptIn,
	hasRewriterSoftOptIn,
	acceptRewriterSoftOptIn,
	buildComposerWriterCreateOptions,
	buildComposerWriterSharedContext,
	formatWriterConstraintTargetLabel,
	normalizeWriterProviderIdentifiers,
	toWriterConstraintProviders,
	writerLengthForMaxCharacters,
	type ComposerWriterConstraintProvider,
	type ComposerWriterCreateCoreOptions,
	type ComposerWriterDraftConstraints,
	type ComposerWriterLength,
	buildComposerRewriterCreateOptions,
	buildComposerRewriterCreateOptionsFromAction,
	type BuildComposerRewriterCreateOptionsInput,
	type ComposerRewriterCreateCoreOptions,
	formatWriterProviderConstraintTooltip
} from '$lib/ai-writer/utils';

export {
	WriterPresenter,
	type WriterUiPhase,
	type RewriterUiGate,
	type WriterRunWriteOptions,
	type WriterChatMessageViewModel,
	type WriterChatRole
} from '$lib/ai-writer/Writer.presenter.svelte';
